/*
Write a program to create a class called Employee, having instance 
variables like name, age, salary and empno. Initialize all the 
instance members using constructor and empno should be auto 
generated by the program. Create an array of objects to define 10 
Employees. 
 */
import java.util.Scanner;
class Employee{
    String name;
    int age,empno,sal;

    Employee(){
        name="";
        empno=0;
        age=0;
        sal=0;
    }
    public void set()
    {
        Scanner sc=new Scanner(System.in);
        //\n
        System.out.print("Enter emp name:");
        name=sc.nextLine();
        System.out.print("Enter emp age:");
        age=sc.nextInt();
        System.out.print("Enter emp sal:");
        sal=sc.nextInt();
    }
    public void display()
    {
        System.out.println("emp name:"+name);
        System.out.println("emp age:"+age);
        System.out.println("emp sal:"+sal);
    }
}
public class Practical24 {
    public static void main(String[] args) {
        System.out.print("No. of emp:");
        int empno=1;
        Scanner sc=new Scanner(System.in);
        int n=sc.nextInt();
        Employee[] e=new Employee[n];
        for (int i = 0; i < n; i++) {
            e[i]=new Employee();
            e[i].set();
        }
        sc.close();
        for (int i = 0; i < n; i++) {
            System.out.println("emp no:"+empno);
            empno++;
            e[i].display();
        }
    }
}

/*
OUTPUT:
No. of emp:2
Enter emp name:Krish Patel
Enter emp age:20
Enter emp sal:50000
Enter emp name:Diya Patel
Enter emp age:20
Enter emp sal:90000
emp no:1
emp name:Krish Patel
emp age:20
emp sal:50000
emp no:2
emp name:Diya Patel
emp age:19
emp sal:90000
 */